MDScreen:
    name: 'dt'
    MDLabel:
        text: 'Data-Table'
        pos_hint: {'center_x': 0.75, 'center_y': 0.90}
        font_size: 35
    MDRoundFlatButton:
        text: 'Show table'
        on_press: app.get_dt()
    #MDRoundFlatButton:
    #    text: 'Close table'
    #    on_press: app.close_dt()
    AnchorLayout:
        id: anch
        pos_hint: {'center_x': 0.50, 'center_y': 0.50}
